In [2]:
import pandas as pd

In [5]:
df = pd.read_csv("output/Kmeans/speeches_with_parlinfo_kmeans.csv")

df.head()

,basepk,speechtext,speakername,year,speechdate,speakerposition,maintopic,speechtext_oringinal,speakerparty,speechtext_word_count,...,date_of_death,is_mp_matched,party_at_date,riding_at_date,province_at_date,party_simplified,cluster,cluster_distance,second_cluster,second_cluster_distance
0,2198843,member may note receiv copi hansard deliv morn...,Marcel Joseph Aimé Lambert,1963,1963-01-22,Speaker of the House of Commons,BUSINESS OF THE HOUSE,Hon. members may have noted that they have not...,Progressive Conservative,78,...,2000-09-24,True,Progressive Conservative Party,Edmonton West,Alberta,Conservative/Progressive Conservative,3,0.987918,7,0.997085
1,2198851,wish tabl bilingu text instrument adopt sessio...,Michael Starr,1963,1963-01-22,Minister of Labour,INTERNATIONAL LABOUR CONFERENCE,I wish to table the bilingual texts of the ins...,Progressive Conservative,132,...,2000-03-16,True,Progressive Conservative Party,Ontario,Ontario,Conservative/Progressive Conservative,9,0.978530,3,0.982880
2,2199017,chairman committe whole bound admiss reject ev...,Gordon Campbell Chown,1963,1963-01-22,Deputy Speaker and Chair of Committees of the ...,MILDRED DAWSON MEAKINS,The chairman and the committee of the whole ar...,Progressive Conservative,57,...,2002-07-31,True,Progressive Conservative Party,Winnipeg South,Manitoba,Conservative/Progressive Conservative,16,0.968756,3,0.993059
3,2199034,way affect case may valid file find follow que...,Gordon Campbell Chown,1963,1963-01-22,Deputy Speaker and Chair of Committees of the ...,MILDRED DAWSON MEAKINS,This will not in any way adversely affect your...,Progressive Conservative,153,...,2002-07-31,True,Progressive Conservative Party,Winnipeg South,Manitoba,Conservative/Progressive Conservative,3,0.983459,7,0.988222
4,2199095,mr speaker wish inform hous part continu effor...,John George Diefenbaker,1963,1963-01-23,Prime Minister; President of the Privy Council,* PENSIONS,"Mr. Speaker, I wish to inform the house that a...",Progressive Conservative,129,...,1979-08-16 (Died in Office),True,Progressive Conservative Party,Prince Albert,Saskatchewan,Conservative/Progressive Conservative,10,0.983564,7,0.988985

In [8]:
df["distance_diff"] = - df["cluster_distance"] + df["second_cluster_distance"]
df["distance_diff"].describe()

KeyError: 'cluster_distance'

In [9]:
df = pd.read_csv("output/speeches_with_parlinfo.csv")
df.describe()

,basepk,year,speechtext_word_count,speech_length_words,person_id
count,1.220540e+05,122054.000000,122054.000000,122054.000000,121040.000000
mean,3.179297e+06,1978.758844,153.658954,153.658954,882.075578
std,5.085280e+05,8.730967,172.123370,172.123370,494.608770
min,2.198843e+06,1963.000000,50.000000,50.000000,1.000000
25%,2.766076e+06,1971.000000,62.000000,62.000000,440.000000
50%,3.217122e+06,1979.000000,85.000000,85.000000,920.000000
75%,3.639866e+06,1987.000000,161.000000,161.000000,1270.000000
max,3.952199e+06,1993.000000,1147.000000,1147.000000,1765.000000

In [ ]:
list = df['is_mp_matched'].tolist()
s = set(list)
print(s)

{False, True}